version: "3.9"

services:
  mariadb:
    container_name: mariadb
    # restart: always
    env_file: .env
    build: ./requirements/mariadb
    volumes:
      - db_volume:/var/lib/mysql
    expose:
      - 3306
    networks:
      - db_network

  wordpress:
    container_name: wordpress
    # restart: always
    depends_on:
      - mariadb
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
    build: ./requirements/wordpress
    volumes:
      - wp_volume:/var/www/html
    working_dir: /var/www/html
    links:
      - mariadb
    expose:
      - 9000
    networks:
      - db_network

  nginx:
    container_name: nginx
    # restart: always
    env_file: .env
    build: ./requirements/nginx
    volumes:
      - wp_volume:/var/www/html
    ports:
      - '443:443'
    networks:
      - db_network

volumes:
  wp_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/hyunkkim/inception/volumes/wordpress

  db_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/hyunkkim/inception/volumes/mariadb

networks:
  db_network:
    driver: bridge
