version: "3.9"

services:
  nginx:
    container_name: nginx
    env_file: .env
    build: ./requirements/nginx
    ports:
      - '443:443'

  mariadb:
    container_name: mariadb
    env_file: .env
    build: ./requirements/nginx
    volumes:
      - /home/hyunkkim/data/mariadb:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - db_network

  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    env_file: .env
    build: ./requirements/wordpress
    volumes:
      - /home/hyunkkim/data/wordpress:/var/www/html
    working_dir: /var/www/html
    networks:
      - db_network

networks:
  db_network:
    driver: bridge
