version: "3.9"

services:
  nginx:
    container_name: nginx
    env_file: .env
    build: ./requirements/nginx
    ports:
      - '443:443'

  wordpress:
    container_name: wordpress
    env_file: .env
    build: ./requirements/wordpress
    volumes:
      - /home/hyunkkim/data:/var/www/html
    working_dir: /var/www/html

