# Bonus Docker compose file

version: "3.8"

services:
  mariadb:
    container_name: mariadb
    restart: always
    env_file: .env_bonus
    build: ../mariadb
    volumes:
      - db_volume:/var/lib/mysql
    expose:
      - 3306
    networks:
      - db_network

  redis:
    container_name: redis
    restart: always
    env_file: .env_bonus
    build: ./redis
    ports:
      - '6379:6379'
    networks:
      - db_network
    volumes:
      - wp_volume:/data

  vsftpd:
    container_name: vsftpd
    restart: always
    env_file: .env_bonus
    build: ./vsftpd
    ports:
      - '20:20'
      - '21:21'
      - '30001:30001'
    networks:
      - db_network
    volumes:
      - wp_volume:/home/vsftpd

  adminer:
    container_name: adminer
    restart: always
    build: ./adminer
    depends_on:
      - mariadb
    expose:
      - 8080
    networks:
      - db_network
    working_dir: /data

  wordpress:
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
    env_file: .env_bonus
    build: ./wordpress
    volumes:
      - wp_volume:/var/www/html
    working_dir: /var/www/html
    expose:
      - 9000
    networks:
      - db_network

  mkdocs:
    container_name: mkdocs
    restart: always
    build: ./mkdocs
    expose:
      - 8000
    networks:
      - db_network
    volumes:
      - bonus_volume:/data
    working_dir: /data/inception

  static_web:
    container_name: static_web
    restart: always
    build: ./static_web
    expose:
      - 8001
    networks:
      - db_network
    volumes:
      - bonus_volume:/data
    working_dir: /data/static-web

  nginx:
    container_name: nginx
    restart: always
    depends_on:
      - mariadb
      - wordpress
      - mkdocs
    env_file: .env_bonus
    build: ./nginx
    volumes:
      - wp_volume:/var/www/html
    ports:
      - '443:443'
    networks:
      - db_network

volumes:
  wp_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
        #device: /Users/hyunkkim/inception/volumes/wordpress
      device: /home/hyunkkim/data/wordpress

  db_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
        #device: /Users/hyunkkim/inception/volumes/mariadb
      device: /home/hyunkkim/data/mariadb

  bonus_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
        #device: /Users/hyunkkim/inception/volumes/mariadb
      device: /home/hyunkkim/data/bonus

networks:
  db_network:
    driver: bridge
